### ISSUE TITLE
"Quick switch graphics..." not working

### ISSUE THREAD

**Issue by Sadi58** [fredldotme/amd-indicator#3]
Everything else seems OK, but when I click "Quick switch graphics..." it only shows a dialogbox "X Restarting..." without any effect at all -- even if I manually log out and log in, I still have the same gpu. It seems "dgpuon" and "igpuon" scripts need "gksudo" inserted or "sudoers" revised. Also, switching to "dgpu" will need full restart instead of logging out and logging in, otherwise I get "low graphics" error message...

**Comment by manhtukhang** [comment]
I don't think so:

``` sh
SUDOERSTRING="%amdindicator ALL=NOPASSWD: /usr/lib/amdindicator/igpuon, /usr/lib/amdindicator/dgpuon"
```

**Comment by Sadi58** [comment]
I see that, but it seems this "sudoerstring" doesn't have any effect somehow...
Manually inserting "gksudo" before "/usr/lib/amdindicator/igpuon" and "/usr/lib/amdindicator/dgpuon" in the indicator file didn't work either, although entering terminal command "gksudo /usr/lib/amdindicator/igpuon" worked... Weird...

**Comment by fredldotme** [comment]
There are several problems with AMD Indicator:
1) I haven't taken a look at it for a year, as I don't have the hardware to run it anymore.
2) Depending on the version of your Distro, this might or might not work.
Except for Ubuntu 12.04, there have always been serious problems when switching between the GPUs. I remember trying to get this to work in 12.10, and the Catalyst driver tried to access symbols of the Intel driver, that have changed/were not there anymore, so X crashed when logging out in and in instead of restarting.
3) The install script is doing unnecessary stuff. The new PRIME indicator doesn't add new users, write into the default sudoers file, etc.
So the AMD Indicator install script should be brought up to date. If someone want's to do this, here is the reference install script for PRIME Indicator: https://github.com/beidl/prime-indicator/blob/master/setup.sh

There are a few forks of AMD Indicator available on GitHub, so maybe they have fixed some of the issues that you are experiencing.

**Comment by Sadi58** [comment]
Thanks. I think I've found a fix. Would you like to appoint me as a collaborator or send you the changes that have worked?

**Comment by fredldotme** [comment]
I'll do it as quickly as possible

**Comment by fredldotme** [comment]
If I could give you a tiny advice:
I'd suggest you modify the setup script to match the PRIME indicators setup script, as currently the AMD one does nasty things like directly modify /etc/sudoers without validation, also it unnecessarily adds a user account.
